dbdata:
    image: postgres
    command: "true"

db:
    extends: 
        file: common.yml
        service: db_base
    volumes_from:
        - dbdata
    ports:
        - "9432:5432"
frontend:
  build: frontend/
  command: gulp
  ports:
        - "4000:4000"
        - "4001:4001"
  volumes:
      - "./frontend:/frontend"
      - "./frontend/dist:/dist"
      - "./frontend/src:/src"      
      - "./frontend/package.json:/package.json"
      - "./frontend/gulpfile.js:/gulpfile.js"
  links:
      - "backend"
backend:
    extends: 
        file: common.yml
        service: backend_base
    ports:
        - "8000:8000"
    volumes:
        - "./backend:/src"
        - "./frontend/dist:/static"
    links:
        - db
    environment:
        DJANGO_SETTINGS_MODULE: tracker.settings